'use strict';
// tests/arc-send-gate.test.js (2026-10-06): the gate on a SCRATCH policy and log. Never touches /etc/apex or data/send-gate.
const fs = require('fs'), os = require('os'), path = require('path');
const D = fs.mkdtempSync(path.join(os.tmpdir(), 'send-gate-test-'));
fs.mkdirSync(path.join(D, 'log'));
const KILL = path.join(D, 'STOP');
const policy = JSON.parse(fs.readFileSync('/etc/apex/send-gate.json', 'utf8'));
policy.kill_file = KILL;
policy.senders['t-shadow'] = { mode: 'shadow', wallets: ['0x0ba8d43e0176324b5a6ae68e64c37f64e734ae73'], global_destinations: true, per_tx_usdc: 1, per_day_usdc: 2 };
fs.writeFileSync(path.join(D, 'policy.json'), JSON.stringify(policy));
process.env.SEND_GATE_DIR = D; process.env.SEND_GATE_POLICY = path.join(D, 'policy.json');
const G = require('/root/apex-faucet/lib/arc-send-gate.js');
const RECV = '0xd334ab5151c624cada654854e2879903dc4217ed', OPER = '0x024b82335c29fa5606a8ea5c1d24fc9ead50700c', STRANGER = '0x' + '42'.repeat(20);
let fail = 0; const ok = (c, m) => { console.log((c ? 'ok   ' : 'FAIL ') + m); if (!c) fail++; };
const base = { source: 'arc-gas-refill', chain: 'arc', chainId: 5042, from: RECV, to: OPER, usdc: 0.7 };
let d = G.check(base); ok(d.allow && d.decision === 'allow', 'refill 0.7 to the operator: allowed');
d = G.check(base); ok(!d.allow && /per-day cap/.test(d.reasons.join()), 'a second refill the same day: denied by the daily cap');
G.release(base, 'simulated failure'); d = G.check(base); ok(d.allow, 'after a release the allowance is back');
G.release(base, 'test');
G.release(Object.assign({}, base, { usdc: 50 }), 'planted: more than was taken'); ok(!G.check(Object.assign({}, base, { usdc: 1.3 })).allow && G.check(Object.assign({}, base, { usdc: 0.05 })).allow, 'a release never gives back more than was taken today');
G.release(Object.assign({}, base, { usdc: 0.05 }), 'test');
ok(!G.check(Object.assign({}, base, { usdc: 1.3 })).allow, 'over the per-transaction cap (1.2): denied');
ok(!G.check(Object.assign({}, base, { to: STRANGER, usdc: 0.1 })).allow, 'a stranger as destination: denied');
ok(!G.check(Object.assign({}, base, { to: '0x53fb2e89834050afaa9b3090a1fc9d1064615805', usdc: 0.1 })).allow, 'the shared list is not open to a sender without global_destinations');
ok(!G.check(Object.assign({}, base, { from: OPER, usdc: 0.1 })).allow, 'a wallet the sender is not registered for: denied');
ok(!G.check(Object.assign({}, base, { chainId: 1, usdc: 0.1 })).allow, 'a wrong chain id: denied');
ok(!G.check(Object.assign({}, base, { source: 'nobody', usdc: 0.1 })).allow, 'an unknown sender: denied');
ok(!G.check(Object.assign({}, base, { usdc: 'x' })).allow, 'an amount that is not a number: denied');
ok(!G.check(Object.assign({}, base, { usdc: 0.1, tokens: { ['0x' + '99'.repeat(20)]: 5 } })).allow, 'a token the sender may not move: denied');
fs.writeFileSync(KILL, 'stop'); ok(!G.check(Object.assign({}, base, { usdc: 0.1 })).allow, 'kill file present: denied'); fs.unlinkSync(KILL);
d = G.check({ source: 't-shadow', chain: 'arc', chainId: 5042, from: '0x0ba8d43e0176324b5a6ae68e64c37f64e734ae73', to: STRANGER, usdc: 0.5 });
ok(d.allow && d.decision === 'would-deny', 'shadow mode: a breach is logged as would-deny and the send is not stopped');
ok(G.check({ source: 't-shadow', chain: 'arc', chainId: 5042, from: '0x0ba8d43e0176324b5a6ae68e64c37f64e734ae73', to: '0x53fb2e89834050afaa9b3090a1fc9d1064615805', usdc: 0.5 }).decision === 'allow', 'shadow sender with the shared list: the faucet pot is allowed');
fs.writeFileSync(process.env.SEND_GATE_POLICY, '{broken'); ok(!G.check(Object.assign({}, base, { usdc: 0.1 })).allow, 'an unreadable policy: denied (fail closed)');
fs.mkdirSync(path.join(D, 'log', '.lock')); const t0 = Date.now(); const dl = G.check(Object.assign({}, base, { usdc: 0.1 }));
ok(!dl.allow && /lock busy/.test(dl.reasons.join()) && Date.now() - t0 >= 9000, 'a lock held by someone else: denied after 10 s (fail closed)');
const log = fs.readFileSync(path.join(D, 'log', 'decisions.ndjson'), 'utf8').trim().split('\n').map(JSON.parse);
ok(log.every((r) => r.at && r.decision), 'every decision is in the log (' + log.length + ' rows)');
ok(!fs.existsSync('/root/apex-faucet/data/send-gate/log/decisions.ndjson') || !fs.readFileSync('/root/apex-faucet/data/send-gate/log/decisions.ndjson', 'utf8').includes('t-shadow'), 'the live log was not touched');
fs.rmSync(D, { recursive: true, force: true });
process.exit(fail ? 1 : 0);
